# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

def findTheDifference(s, t):
  return chr(sum(map(ord, t)) - sum(map(ord, s)))

input1 = "abcd"
input2 = "abcde"
print(findTheDifference(input1, input2)) # e

input1 = ""
input2 = "y"
print(findTheDifference(input1, input2)) # y